SELECT 
df.ID_FXO AS "ID",
da.ID_TFX_ASS AS "ID_FLUXO",
df.NUMERO_FXO AS "NUM",
df.ANO_FXO AS "ANO_DOCUMENTO",
df.TITULO_FXO AS "ASSUNTO",
--CONTEUDO
--PRIORIDADE
--CODIGO
--de_usuario_id	
--de_setor_id	
--para_usuario_id	
--para_setor_id	
--de_contato_id	
--para_contato_id
df.DTA_INC_FXO AS "DATA_HORA_RECEBIMENTO", --separar em dt e hr 
--data_hora_recebimento_gmt
df.ID_ASS_FXO,
da.DESCRICAO_ASS,
df.ID_UTRDE_FXO ,
df.STATUS_FXO,
df.SIGILOSO_FXO, 
df.TEMANEXO_FXO, 
df.ID_ARQ_FXO ,
df.ARQUIVADO_FXO, 
df.DATATRAMITE_FXO ,
df.QTDTRAMITE_FXO,
df.LOGIN_INC_FXO,
df.DTA_INC_FXO ,
df.LOGIN_ALT_FXO,
df.DTA_ALT_FXO,
dut.ID_UTR,
dut.ID_ORG_UTR,
do.NOME_ORG,
au.LOGIN_USR
FROM DOC_FLUXO df

-- ASSUNTO
LEFT JOIN DOC_ASSUNTO da 
ON df.ID_ASS_FXO  = da.ID_ASS 

-- UNIDADE DE TRAMITAÇÃO
LEFT JOIN DOC_UNIDADE_TRAMITACAO dut
ON df.ID_UTRDE_FXO = dut.ID_UTR 

-- ORGANOGRAMA TRAMITACAO
LEFT JOIN DOC_ORGANOGRAMA do 
ON dut.ID_ORG_UTR = do.ID_ORG 

-- USUARIO TRAMITACAO
LEFT JOIN AUT_USUARIO au  
ON dut.ID_USR_UTR = au.ID_USR 

-- USUARIO TRAMITACAO
LEFT JOIN AUT_USUARIO au  
ON dut.ID_USR_UTR = au.ID_USR 

-- UNIR PRIMEIROS DESPACHOS CONTEUDO 








