-- unidade de tramitação + tramitacoes (todas, inclusive repetidas)
CREATE VIEW dados_tramitacao as
SELECT 
ID_FTO, 
ID_FTR_FTO, 
ID_UTRDE_FTO, 
ID_UTRPARA_FTO,
duto.TIPO_UTR,
duto.ID_ORG_UTR AS ID_ORG_UTR_O,
duto.ID_USR_UTR AS ID_USR_UTR_O,
auo.TIPO_USR AS TIPO_USR_O,
CASE
	WHEN auo.TIPO_USR  = 0 THEN 'USUARIO INTERNO'
	WHEN auo.TIPO_USR  = 1 THEN 'CONTATO'
	WHEN auo.TIPO_USR  = 2 THEN 'USUARIO DE INTEGRACAO / INTERNO'
	ELSE 'SETOR/ORGANOGRAMA'
	END AS "TIPO_USR_ORIGEM",

dutd.ID_ORG_UTR AS ID_ORG_UTR_D,
dutd.ID_USR_UTR AS ID_USR_UTR_D,
aud.TIPO_USR AS TIPO_USR_D,
CASE
	WHEN aud.TIPO_USR = 0 THEN 'USUARIO INTERNO'
	WHEN aud.TIPO_USR  = 1 THEN 'CONTATO'
	WHEN aud.TIPO_USR  = 2 THEN 'USUARIO DE INTEGRACAO / INTERNO'
	ELSE 'SETOR/ORGANOGRAMA'
	END AS "TIPO_USR_DESTINO"
FROM DOC_FLUXO_TRAMITACAO dft

LEFT JOIN DOC_UNIDADE_TRAMITACAO duto
ON duto.ID_UTR  = dft.ID_UTRDE_FTO 

LEFT JOIN DOC_UNIDADE_TRAMITACAO dutd
ON dutd.ID_UTR  = dft.ID_UTRPARA_FTO 

LEFT JOIN AUT_USUARIO auo
ON auo.ID_USR = duto.ID_USR_UTR

LEFT JOIN AUT_USUARIO aud
ON aud.ID_USR = dutd.ID_USR_UTR